In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_train=pd.read_csv("train.csv")
df_train.head()

,Product_id,Stall_no,instock_date,Market_Category,Customer_name,Loyalty_customer,Product_Category,Grade,Demand,Discount_avail,charges_1,charges_2 (%),Minimum_price,Maximum_price,Selling_Price
0,BRAE2NF6JA5GUEXG,37.0,2015-08-22 18:36:12.000,2,Lillyann,Yes,Fashion,1,68,0.0,376.0,11.0,2983.0,4713.0,4185.947700
1,TUNE8SFB6RJN2HSD,38.0,2016-03-27 21:19:13.000,24,Klynn,Yes,Fashion,0,51,0.0,397.0,12.0,7495.0,10352.0,9271.490256
2,BRAEAR7WZPQGPBZU,9.0,2015-08-18 19:25:22.000,447,Ridge,Yes,Child_care,0,10,0.0,250.0,9.0,5752.0,7309.0,6785.701362
3,WATDZ2ZQ8JPDHCTJ,50.0,2016-03-28 21:53:01.000,23,Abran,Yes,Educational,2,48,0.0,144.0,13.0,5090.0,20814.0,13028.917824
4,JWSEBUKYQPMBZ3RK,7.0,2016-03-29 22:58:53.000,63,Dustyn,Yes,Repair,1,35,1.0,211.0,4.0,2430.0,9261.0,906.553935

In [3]:
df_test=pd.read_csv("test.csv")
df_test

,Product_id,Stall_no,instock_date,Market_Category,Customer_name,Loyalty_customer,Product_Category,Grade,Demand,Discount_avail,charges_1,charges_2 (%),Minimum_price,Maximum_price
0,SCHE4YSTDVPVZVXW,39.0,2016-01-13 07:45:08.000,205,Ivanka,No,Fashion,0,90,0,380.0,16.0,2576.0,3340
1,ACCEGCATKHNRXUHW,49.0,2015-08-23 20:37:05.000,3,Isaak,Yes,Fashion,0,87,0,393.0,16.0,1202.0,1955
2,NKCE6GJ5XVJDXNNZ,1.0,2015-11-14 18:12:39.000,183,Analiese,No,Technology,2,55,0,493.0,9.0,7175.0,15715
3,NKCEB8BK3ZXDHDHM,8.0,2015-11-21 04:56:19.000,358,Rusty,Yes,Child_care,3,86,0,303.0,16.0,5404.0,13078
4,TOPEFDXSAHRNPF94,33.0,2015-05-06 15:09:46.000,167,Eloise,No,Technology,0,27,0,567.0,16.0,4069.0,6244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3425,BBAE9K7BXFUTDNBK,9.0,2015-08-15 21:17:17.000,58,Davion,Yes,Pet_care,0,39,0,117.0,5.0,3094.0,4674
3426,RTRDYPA4PJHCJCGF,30.0,2015-12-04 01:51:47.000,358,Maiah,Yes,Technology,3,17,0,509.0,6.0,3384.0,14105
3427,TUNE8FWQBS7TVVT7,14.0,2016-03-28 20:55:47.000,106,Gwendolen,Yes,Educational,0,36,0,150.0,17.0,710.0,10894
3428,NKCEGMUABCRGUZPE,1.0,2015-05-23 07:41:36.000,104,Addilynn,Yes,Child_care,0,63,0,325.0,15.0,1477.0,5165
3429,RNGE7M92KAQWUBCS,3.0,2015-08-16 22:19:46.000,165,Charlize,No,Repair,0,92,1,228.0,9.0,5538.0,7506

In [4]:
df_train.describe()

,Stall_no,Market_Category,Grade,Demand,Discount_avail,charges_1,charges_2 (%),Minimum_price,Maximum_price,Selling_Price
count,6363.000000,6368.000000,6368.000000,6368.000000,6330.000000,6170.000000,6163.000000,6330.000000,6025.000000,6327.000000
mean,25.309445,199.340609,0.643687,50.921168,0.140442,264.514100,10.146195,3531.349763,6432.545892,4563.242592
std,14.328980,170.275570,1.025092,29.091922,0.347473,124.483056,4.318339,2194.729604,3716.177364,2979.102408
min,1.000000,0.000000,0.000000,1.000000,0.000000,100.000000,1.000000,1.000000,404.000000,-6062.470000
25%,13.000000,55.000000,0.000000,26.000000,0.000000,163.000000,7.000000,1879.250000,3918.000000,2450.005280
50%,25.000000,132.000000,0.000000,51.000000,0.000000,252.000000,10.000000,3157.500000,5634.000000,4210.384640
75%,37.000000,403.000000,2.000000,76.000000,0.000000,314.000000,14.000000,4697.000000,8126.000000,6167.643252
max,50.000000,471.000000,3.000000,100.000000,1.000000,649.000000,17.000000,17580.000000,58812.000000,22638.325941

In [5]:
df_test.describe()

,Stall_no,Market_Category,Grade,Demand,Discount_avail,charges_1,charges_2 (%),Minimum_price,Maximum_price
count,3429.000000,3430.000000,3430.000000,3430.000000,3430.000000,3394.000000,3425.000000,3416.000000,3430.000000
mean,25.633421,196.693878,0.667638,49.917493,0.146356,265.484973,10.436204,3444.206089,6234.062391
std,14.389747,168.832500,1.045914,28.587214,0.353514,125.325455,4.232382,2178.418557,3575.968650
min,1.000000,0.000000,0.000000,1.000000,0.000000,100.000000,1.000000,124.000000,163.000000
25%,13.000000,55.000000,0.000000,26.000000,0.000000,162.000000,7.000000,1834.000000,3819.000000
50%,26.000000,124.000000,0.000000,50.000000,0.000000,252.000000,11.000000,3060.500000,5431.000000
75%,38.000000,358.000000,2.000000,74.000000,0.000000,319.000000,14.000000,4606.500000,7796.500000
max,50.000000,471.000000,3.000000,100.000000,1.000000,648.000000,17.000000,17182.000000,27954.000000

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6368 entries, 0 to 6367
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_id        6368 non-null   object
 1   Stall_no          6363 non-null   float64
 2   instock_date      6368 non-null   object
 3   Market_Category   6368 non-null   int64
 4   Customer_name     6157 non-null   object
 5   Loyalty_customer  6368 non-null   object
 6   Product_Category  6368 non-null   object
 7   Grade             6368 non-null   int64
 8   Demand            6368 non-null   int64
 9   Discount_avail    6330 non-null   float64
 10  charges_1         6170 non-null   float64
 11  charges_2 (%)     6163 non-null   float64
 12  Minimum_price     6330 non-null   float64
 13  Maximum_price     6025 non-null   float64
 14  Selling_Price     6327 non-null   float64
dtypes: float64(7), int64(3), object(5)
memory usage: 746.4+ KB

In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3430 entries, 0 to 3429
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_id        3430 non-null   object
 1   Stall_no          3429 non-null   float64
 2   instock_date      3430 non-null   object
 3   Market_Category   3430 non-null   int64
 4   Customer_name     3377 non-null   object
 5   Loyalty_customer  3430 non-null   object
 6   Product_Category  3430 non-null   object
 7   Grade             3430 non-null   int64
 8   Demand            3430 non-null   int64
 9   Discount_avail    3430 non-null   int64
 10  charges_1         3394 non-null   float64
 11  charges_2 (%)     3425 non-null   float64
 12  Minimum_price     3416 non-null   float64
 13  Maximum_price     3430 non-null   int64
dtypes: float64(4), int64(5), object(5)
memory usage: 375.3+ KB

In [8]:
#Drop unnecessary columns
df_train.drop(["Product_id","Customer_name"],axis=1,inplace=True)
df_test.drop(["Product_id","Customer_name"],axis=1,inplace=True)

In [9]:
#Convert instock date to datetime
df_train["instock_date"]=pd.to_datetime(df_train["instock_date"])
df_test["instock_date"]=pd.to_datetime(df_test["instock_date"])

In [10]:
for df in [df_train,df_test]:
    df["Year"]=df["instock_date"].dt.year
    df["Month"]=df["instock_date"].dt.month
    df["Day"]=df["instock_date"].dt.day
    df["Hour"]=df["instock_date"].dt.hour

In [11]:
df_train.drop("instock_date",axis=1,inplace=True)
df_test.drop("instock_date",axis=1,inplace=True)

In [12]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6368 entries, 0 to 6367
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Stall_no          6363 non-null   float64
 1   Market_Category   6368 non-null   int64
 2   Loyalty_customer  6368 non-null   object
 3   Product_Category  6368 non-null   object
 4   Grade             6368 non-null   int64
 5   Demand            6368 non-null   int64
 6   Discount_avail    6330 non-null   float64
 7   charges_1         6170 non-null   float64
 8   charges_2 (%)     6163 non-null   float64
 9   Minimum_price     6330 non-null   float64
 10  Maximum_price     6025 non-null   float64
 11  Selling_Price     6327 non-null   float64
 12  Year              6368 non-null   int32
 13  Month             6368 non-null   int32
 14  Day               6368 non-null   int32
 15  Hour              6368 non-null   int32
dtypes: float64(7), int32(4), int64(3), object(2)
memory usage: 696.6+ KB

In [13]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3430 entries, 0 to 3429
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Stall_no          3429 non-null   float64
 1   Market_Category   3430 non-null   int64
 2   Loyalty_customer  3430 non-null   object
 3   Product_Category  3430 non-null   object
 4   Grade             3430 non-null   int64
 5   Demand            3430 non-null   int64
 6   Discount_avail    3430 non-null   int64
 7   charges_1         3394 non-null   float64
 8   charges_2 (%)     3425 non-null   float64
 9   Minimum_price     3416 non-null   float64
 10  Maximum_price     3430 non-null   int64
 11  Year              3430 non-null   int32
 12  Month             3430 non-null   int32
 13  Day               3430 non-null   int32
 14  Hour              3430 non-null   int32
dtypes: float64(4), int32(4), int64(5), object(2)
memory usage: 348.5+ KB

In [14]:
#Encode categorical values for ordinal data
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df_train["Loyalty_customer"]=LabelEncoder().fit_transform(df_train["Loyalty_customer"])
df_test["Loyalty_customer"]=LabelEncoder().fit_transform(df_test["Loyalty_customer"])

In [15]:
#Encode categorical values for nominal data
df_train=pd.get_dummies(df_train,columns=["Product_Category"],drop_first=True)
df_test=pd.get_dummies(df_test,columns=["Product_Category"],drop_first=True)

In [16]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6368 entries, 0 to 6367
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Stall_no                      6363 non-null   float64
 1   Market_Category               6368 non-null   int64
 2   Loyalty_customer              6368 non-null   int64
 3   Grade                         6368 non-null   int64
 4   Demand                        6368 non-null   int64
 5   Discount_avail                6330 non-null   float64
 6   charges_1                     6170 non-null   float64
 7   charges_2 (%)                 6163 non-null   float64
 8   Minimum_price                 6330 non-null   float64
 9   Maximum_price                 6025 non-null   float64
 10  Selling_Price                 6327 non-null   float64
 11  Year                          6368 non-null   int32
 12  Month                         6368 non-null   int32
 13  Day                           6368 non-null   int32
 14  Hour                          6368 non-null   int32
 15  Product_Category_Cosmetics    6368 non-null   bool
 16  Product_Category_Educational  6368 non-null   bool
 17  Product_Category_Fashion      6368 non-null   bool
 18  Product_Category_Home_decor   6368 non-null   bool
 19  Product_Category_Hospitality  6368 non-null   bool
 20  Product_Category_Organic      6368 non-null   bool
 21  Product_Category_Pet_care     6368 non-null   bool
 22  Product_Category_Repair       6368 non-null   bool
 23  Product_Category_Technology   6368 non-null   bool
dtypes: bool(9), float64(7), int32(4), int64(4)
memory usage: 702.8 KB

In [17]:
#Convert boolean values into int
bool_cols=df_train.select_dtypes(include=["bool"]).columns
bool_cols=df_test.select_dtypes(include=["bool"]).columns
df_train[bool_cols]=df_train[bool_cols].astype(int)
df_test[bool_cols]=df_test[bool_cols].astype(int)

In [18]:
#handle missing values in numerical data
num_col = df_train.select_dtypes(include=["float64","int64"]).columns
df_train[num_col]=df_train[num_col].fillna(df_train[num_col].median())

num_col = df_test.select_dtypes(include=["float64","int64"]).columns
df_test[num_col]=df_test[num_col].fillna(df_test[num_col].median())

In [19]:
df_train.isnull().sum()

Stall_no                        0
Market_Category                 0
Loyalty_customer                0
Grade                           0
Demand                          0
Discount_avail                  0
charges_1                       0
charges_2 (%)                   0
Minimum_price                   0
Maximum_price                   0
Selling_Price                   0
Year                            0
Month                           0
Day                             0
Hour                            0
Product_Category_Cosmetics      0
Product_Category_Educational    0
Product_Category_Fashion        0
Product_Category_Home_decor     0
Product_Category_Hospitality    0
Product_Category_Organic        0
Product_Category_Pet_care       0
Product_Category_Repair         0
Product_Category_Technology     0
dtype: int64

In [20]:
df_test.isnull().sum()

Stall_no                        0
Market_Category                 0
Loyalty_customer                0
Grade                           0
Demand                          0
Discount_avail                  0
charges_1                       0
charges_2 (%)                   0
Minimum_price                   0
Maximum_price                   0
Year                            0
Month                           0
Day                             0
Hour                            0
Product_Category_Cosmetics      0
Product_Category_Educational    0
Product_Category_Fashion        0
Product_Category_Home_decor     0
Product_Category_Hospitality    0
Product_Category_Organic        0
Product_Category_Pet_care       0
Product_Category_Repair         0
Product_Category_Technology     0
dtype: int64

In [21]:
#Feature Engineering 
df_train["Price_Range"]=df_train["Maximum_price"]-df_train["Minimum_price"]
df_test["Price_Range"]=df_test["Maximum_price"]-df_test["Minimum_price"]

In [22]:
#Separate Features and target
x=df_train.drop("Selling_Price",axis=1)
y=df_train["Selling_Price"]

In [23]:
from sklearn.model_selection import train_test_split
#Train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [24]:
#Train machine learning model
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100,random_state=42)
model.fit(x_train,y_train)

RandomForestRegressor(random_state=42)

In [27]:
#Model Evaluation
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
#Predict on test data
y_preds=model.predict(x_test)

In [28]:
#Calculate evaluation metrics
mae=mean_absolute_error(y_test, y_preds)
mse = mean_squared_error(y_test, y_preds)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_preds)

In [29]:
print(" Mean Absolute Error :", mae)
print(" Mean Squared Error :", mse)
print(" Root Mean Squared Error :", rmse)
print(" R² Score:", r2)

 Mean Absolute Error : 154.20995417158042
 Mean Squared Error : 146200.41640637076
 Root Mean Squared Error : 382.3616304055243
 R² Score: 0.9827773631999629

In [30]:
model.score(x_test,y_test)

0.9827773631999629